// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {mongo} from '../models';

export function CheckKey(arg1:string):Promise<boolean>;

export function GetFrontendFunctions():Promise<main.FrontendFunctions>;

export function GetMongoClient():Promise<mongo.Client>;
