// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckKey(arg1) {
  return window['go']['main']['App']['CheckKey'](arg1);
}

export function GetFrontendFunctions() {
  return window['go']['main']['App']['GetFrontendFunctions']();
}
